"""Manifest for scripts/b1-02-catching-up-with-a-friend.md"""

NAME = "b1_fr_02_friend"

CAST = {
    "Clara":   "XrExE9yKIg1WjnnlVkGX",  # Matilda - warm, professional host (F, EN-base, multilingual)
    "Max":     "iP95p4xoKVk53GoZ742B",  # Chris - charming, down-to-earth host (M, EN-base, multilingual)
    "Lea":     "FvmvwvObRqIHojkEGh5N",  # Adina - young, welcoming, joyful (F, native French)
    "Camille": "AiJXmyKRr43pvJUsR0tP",  # Louise - warm & authentic (F, native French)
}

STREET_SCENE = {
    "key": "STREET",
    "lang": "fr",
    "ambience_prompt": "continuous loopable Parisian street ambience, distant traffic, occasional footsteps, faint café murmur, no music, no words",
    "start_prompt": "footsteps on a city sidewalk that suddenly stop, brief pause, street ambience",
    "end_prompt": "warm laughter of two friends, then Parisian street ambience continuing softly",
    "start_dur": 1.5,
    "end_dur": 2.0,
    "lead": 0.9,
    "tail": 1.5,
    "turn_gap": 0.4,
    "lines": [
        ("Lea", "Camille ?! Ça alors, ça fait un bail !"),
        ("Camille", "Léa ! Je n'en reviens pas ! Comment tu vas ?"),
        ("Lea", "Ça va, ça va, je n'ai pas changé. Et toi, qu'est-ce que tu deviens ?"),
        ("Camille", "Eh bien, j'ai déménagé à Lyon il y a six mois, pour le travail."),
        ("Lea", "Ah oui ? Ça te plaît ?"),
        ("Camille", "Beaucoup, mais tu me manques, toi et le reste de la bande !"),
        ("Lea", "Toi aussi tu nous manques ! Dis, tu es de passage combien de temps ?"),
        ("Camille", "Jusqu'à dimanche. On pourrait se voir un de ces jours, non ?"),
        ("Lea", "Carrément ! Ça te dirait de dîner ensemble demain soir ?"),
        ("Camille", "Ah, demain je suis prise, malheureusement. Mais après-demain, ça marche ?"),
        ("Lea", "Parfait, ça me va très bien !"),
        ("Camille", "Génial. On se tient au courant."),
    ],
}

SEGMENTS = [
    ("sfx", "INTRO_STING", "podcast intro jingle: bright acoustic guitar and light accordion melody, warm French cafe feel, cheerful and inviting, no vocals", 3.5),
    ("speech", "Max", "Bonjour, Clara !", "fr"),
    ("speech", "Clara", "Bonjour, Max ! You know that moment when you bump into someone you haven't seen in ages, right in the street?", "en"),
    ("speech", "Max", "The \"oh my god, IS THAT—\" moment.", "en"),
    ("speech", "Clara", "Exactly that one. Let's listen in.", "en"),
    ("silence", 0.8),

    ("scene", STREET_SCENE),

    ("silence", 2.0),
    ("speech", "Max", "Okay, that was fast and warm — very \"old friends.\" Let's slow it down.", "en"),
    ("speech_multi", "Clara", [("en", "First line out of Léa's mouth:"), ("fr", "Ça fait un bail !")]),
    ("speech_multi", "Max", [
        ("en", "Literally,"),
        ("fr", "bail"),
        ("en", "is a lease — like a rental lease. So this is really \"it's been a whole lease term,\" which in English just means..."),
    ]),
    ("speech", "Clara", "\"It's been ages!\" It's completely idiomatic — don't try to translate it word for word out loud, just learn the whole chunk.", "en"),
    ("speech", "Max", "Ça fait un bail. Ça fait un bail !", "fr"),
    ("speech", "Clara", "Ça fait un bail !", "fr"),
    ("speech", "Max", "Repeat after Clara, or say \"not now.\"", "en"),
    ("silence", 3.5),
    ("speech", "Clara", "Ça fait un bail !", "fr"),
    ("sfx", "SPEAKER_SFX", "loud clear electronic beep, short attention tone, like a recording-start alert, bright and audible", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "bright cheerful bell chime, unmistakably a correct-answer ding, loud and clear, upbeat", 0.7),
    ("silence", 1.8),
    ("speech", "Max", "Great. Now, the natural follow-up question — the one you ask anyone you haven't seen in a while.", "en"),
    ("speech", "Clara", "Qu'est-ce que tu deviens ?", "fr"),
    ("speech", "Max", "Literally \"what are you becoming,\" but it really means \"what have you been up to?\" — what's new in your life.", "en"),
    ("speech_multi", "Clara", [
        ("fr", "Qu'est-ce que tu deviens ?"),
        ("en", "It's informal — the"),
        ("fr", "tu"),
        ("en", "form — so save this one for friends, not your hotel manager."),
    ]),
    ("speech", "Max", "Qu'est-ce que tu deviens ?", "fr"),
    ("silence", 3.5),
    ("speech", "Clara", "Qu'est-ce que tu deviens ?", "fr"),
    ("sfx", "SPEAKER_SFX", "", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "", 0.7),
    ("silence", 1.8),
    ("speech", "Max", "Excellent ! Now here's the part where they actually make a plan. Léa proposes something using the conditional — it's softer, more casual than a direct question.", "en"),
    ("speech", "Clara", "On pourrait se voir un de ces jours.", "fr"),
    ("speech_multi", "Max", [
        ("en", "\"We could see each other one of these days.\""),
        ("fr", "Pourrait"),
        ("en", "is the conditional of"),
        ("fr", "pouvoir"),
        ("en", "— \"could.\" It makes the invitation feel relaxed, no pressure."),
    ]),
    ("speech_multi", "Clara", [("fr", "On pourrait se voir."), ("en", "And then Léa gets more specific...")]),
    ("speech", "Max", "Ça te dirait de dîner ensemble demain soir ?", "fr"),
    ("speech_multi", "Clara", [
        ("fr", "Ça te dirait de..."),
        ("en", "is probably the single most useful invitation phrase in casual French — \"would you feel like...?\" You can drop almost anything after it."),
    ]),
    ("speech", "Max", "Ça te dirait de... ça te dirait de dîner ensemble ?", "fr"),
    ("speech", "Clara", "Ça te dirait de dîner ensemble ?", "fr"),
    ("silence", 3.5),
    ("speech", "Clara", "On pourrait se voir un de ces jours.", "fr"),
    ("sfx", "SPEAKER_SFX", "", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "", 0.7),
    ("silence", 1.8),
    ("speech", "Clara", "Ça te dirait de dîner ensemble demain soir ?", "fr"),
    ("sfx", "SPEAKER_SFX", "", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "", 0.7),
    ("silence", 1.8),
    ("speech", "Max", "Magnifique ! Last piece — Camille can't do tomorrow, so she has to say no without shutting the door.", "en"),
    ("speech", "Clara", "Demain je suis prise, malheureusement. Mais après-demain, ça marche ?", "fr"),
    ("speech_multi", "Max", [
        ("fr", "Je suis prise"),
        ("en", "— \"I'm busy,\" or literally \"I'm taken.\" If you're a man saying it, drop the extra \"e\" —"),
        ("fr", "je suis pris."),
    ]),
    ("speech", "Clara", "Je suis prise. Je suis prise, malheureusement.", "fr"),
    ("speech", "Max", "And then instead of just leaving it there, she immediately offers a different day, and checks if it works with a very handy little phrase...", "en"),
    ("speech", "Clara", "Ça marche ?", "fr"),
    ("speech_multi", "Max", [
        ("en", "\"Does that work?\" — you'll hear"),
        ("fr", "ça marche"),
        ("en", "constantly in French to mean \"that works\" or \"deal.\" And Léa answers with its cousin..."),
    ]),
    ("speech", "Clara", "Ça me va très bien.", "fr"),
    ("speech_multi", "Max", [("en", "\"That works great for me.\" Same idea, slightly more personal —"), ("fr", "va"), ("en", "as in \"suits me.\"")]),
    ("silence", 3.0),
    ("speech", "Clara", "Je suis prise, malheureusement.", "fr"),
    ("sfx", "SPEAKER_SFX", "", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "", 0.7),
    ("silence", 1.8),
    ("speech", "Clara", "Ça marche ?", "fr"),
    ("sfx", "SPEAKER_SFX", "", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "", 0.7),
    ("silence", 1.8),
    ("speech", "Max", "Fantastique !", "fr"),
    ("silence", 3.0),
    ("speech_multi", "Max", [
        ("en", "Now you try the other side of it. A friend just asked you:"),
        ("fr", "Ça te dirait d'aller au cinéma vendredi ?"),
        ("en", "— but you're busy on Friday."),
    ]),
    ("speech", "Clara", "Decline politely, and suggest Saturday instead.", "en"),
    ("silence", 5.0),
    ("speech", "Max", "Here's one natural way to say it:", "en"),
    ("speech", "Clara", "Vendredi je suis prise, mais samedi ça marche pour moi !", "fr"),
    ("speech", "Max", "\"I'm busy Friday, but Saturday works for me!\"", "en"),
    ("silence", 3.0),
    ("speech", "Clara", "So — running into someone unexpectedly...", "en"),
    ("speech", "Max", "Ça fait un bail !", "fr"),
    ("speech", "Clara", "Catching up...", "en"),
    ("speech", "Max", "Qu'est-ce que tu deviens ?", "fr"),
    ("speech", "Clara", "Making — and adjusting — plans.", "en"),
    ("speech_multi", "Max", [("fr", "Ça te dirait de..."), ("en", "and"), ("fr", "ça marche.")]),
    ("speech", "Clara", "Next time, we'll actually go on that dinner and order for two.", "en"),
    ("speech", "Max", "Au revoir !", "fr"),
    ("speech", "Clara", "Au revoir !", "fr"),
    ("sfx", "OUTRO_STING", "podcast outro jingle: same bright acoustic guitar and accordion melody as the intro, but winding down gently, warm French cafe feel, friendly close, no vocals", 3.5),
]
