"""Manifest for scripts/b1-01-cafe-substitution.md"""

NAME = "b1_fr_01_cafe"

CAST = {
    "Clara":     "XrExE9yKIg1WjnnlVkGX",  # Matilda - warm, professional host (F, EN-base, multilingual)
    "Max":       "iP95p4xoKVk53GoZ742B",  # Chris - charming, down-to-earth host (M, EN-base, multilingual)
    "Client":    "KSyQzmsYhFbuOhqj1Xxv",  # "Lea - UGC creator" - dynamic, energetic (F, native French)
    "Boulanger": "UBXZKOKbt62aLQHhc1Jm",  # François Louis - deep, warm, poised (M, native French)
}

BAKERY_SCENE = {
    "key": "BAKERY",
    "lang": "fr",
    "ambience_prompt": "continuous loopable ambience inside a small French bakery, quiet murmuring chatter, soft footsteps, faint oven hum, no music, no words",
    "start_prompt": "small shop door bell, single gentle ding chime as door opens",
    "end_prompt": "small shop door bell chime as door closes, then quiet street ambience begins",
    "start_dur": 1.5,
    "end_dur": 1.8,
    "lead": 1.0,
    "tail": 1.4,
    "turn_gap": 0.4,
    "lines": [
        ("Client", "Bonjour ! Je voudrais un pain au chocolat, s'il vous plaît."),
        ("Boulanger", "Ah, je suis désolé, il n'en reste plus ce matin."),
        ("Client", "Ah bon ? Zut alors..."),
        ("Boulanger", "Mais si vous voulez, je peux vous proposer autre chose. Qu'est-ce que vous en pensez d'un chausson aux pommes ? Il est encore tout chaud."),
        ("Client", "Pourquoi pas ! Il est fait maison ?"),
        ("Boulanger", "Bien sûr, tout est fait maison ici."),
        ("Client", "D'accord, je vais essayer. Et avec ça, un café aussi, s'il vous plaît."),
        ("Boulanger", "Très bien. Ça fera cinq euros quarante."),
        ("Client", "Voilà. Merci beaucoup, bonne journée !"),
        ("Boulanger", "Bonne journée à vous aussi !"),
    ],
}

SEGMENTS = [
    ("sfx", "INTRO_STING", "podcast intro jingle: bright acoustic guitar and light accordion melody, warm French cafe feel, cheerful and inviting, no vocals", 3.5),
    ("speech", "Clara", "Bonjour, Max !", "fr"),
    ("speech", "Max", "Bonjour, Clara ! Alors, qu'est-ce qu'on fait aujourd'hui ?", "fr"),
    ("speech", "Clara", "Today we're tackling something every traveler runs into eventually: you walk into a bakery, you know exactly what you want...", "en"),
    ("speech", "Max", "...and then you hear four words that ruin your morning.", "en"),
    ("speech", "Clara", "Exactly. Let's listen to what happens at the counter.", "en"),
    ("silence", 0.8),

    ("scene", BAKERY_SCENE),

    ("silence", 2.0),
    ("speech_multi", "Max", [("en", "Okay, so her"), ("fr", "pain au chocolat"), ("en", "was a no-go.")]),
    ("speech", "Clara", "Right, and instead of just leaving, she rolled with it. That's the move we're practicing today — staying in the conversation instead of freezing up.", "en"),
    ("speech_multi", "Max", [("en", "Let's break down what the baker said first:"), ("fr", "il n'en reste plus.")]),
    ("speech_multi", "Clara", [
        ("en", "Literally, \"there's none of it left.\" That little word"),
        ("fr", "en"),
        ("en", "is doing a lot of work — it's standing in for"),
        ("fr", "pain au chocolat"),
        ("en", "so he doesn't have to repeat it."),
    ]),
    ("speech", "Max", "Il n'en reste plus.", "fr"),
    ("silence", 0.6),
    ("speech", "Clara", "Il n'en reste plus.", "fr"),
    ("silence", 0.6),
    ("speech", "Clara", "Your turn. Repeat after Max, or say \"not now.\"", "en"),
    ("silence", 3.5),
    ("speech", "Max", "il n'en reste plus", "fr"),
    ("sfx", "SPEAKER_SFX", "loud clear electronic beep, short attention tone, like a recording-start alert, bright and audible", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "bright cheerful bell chime, unmistakably a correct-answer ding, loud and clear, upbeat", 0.7),
    ("silence", 1.8),
    ("speech_multi", "Clara", [("fr", "Bien joué !"), ("en", "Now — how did the baker offer something else instead of just saying \"sorry, no\"?")]),
    ("speech_multi", "Max", [
        ("en", "He said,"),
        ("fr", "Qu'est-ce que vous en pensez d'un chausson aux pommes ?"),
        ("en", "— \"What do you think about an apple turnover?\""),
    ]),
    ("speech_multi", "Clara", [
        ("en", "That's a really natural way to float a suggestion — not just \"do you want X\" but \"what's your take on X.\""),
        ("fr", "Qu'est-ce que vous en pensez de..."),
    ]),
    ("speech", "Max", "Qu'est-ce que vous en pensez de...", "fr"),
    ("speech_multi", "Clara", [
        ("fr", "Qu'est-ce que vous en pensez de..."),
        ("en", "And notice — that's the same"),
        ("fr", "en"),
        ("en", "again, standing in for the thing you're suggesting."),
    ]),
    ("speech_multi", "Max", [
        ("en", "Good ear. And when the customer likes the idea, she doesn't say"),
        ("fr", "oui"),
        ("en", "— she says something much more common in spoken French."),
    ]),
    ("speech", "Clara", "Pourquoi pas !", "fr"),
    ("speech_multi", "Max", [("fr", "Pourquoi pas"), ("en", "— literally \"why not,\" but it lands like an easy, enthusiastic \"sure, why not!\"")]),
    ("speech", "Clara", "Pourquoi pas !", "fr"),
    ("silence", 3.5),
    ("speech", "Max", "Qu'est-ce que vous en pensez de...", "fr"),
    ("sfx", "SPEAKER_SFX", "", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "", 0.7),
    ("silence", 1.8),
    ("speech", "Max", "Pourquoi pas !", "fr"),
    ("sfx", "SPEAKER_SFX", "", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "", 0.7),
    ("silence", 1.8),
    ("speech", "Max", "Qu'est-ce que vous en pensez d'un chausson aux pommes ?", "fr"),
    ("sfx", "SPEAKER_SFX", "", 0.7),
    ("silence", 2.5),
    ("sfx", "CORRECT_SFX", "", 0.7),
    ("silence", 1.8),
    ("speech", "Clara", "Très bien !", "fr"),
    ("silence", 3.0),
    ("speech", "Max", "One more useful bit — when it's time to pay, the baker doesn't say \"it costs.\" He says...", "en"),
    ("speech", "Clara", "Ça fera cinq euros quarante.", "fr"),
    ("speech_multi", "Max", [("fr", "Ça fera"), ("en", "— \"that'll come to\" or \"that'll be.\" You'll hear it at every counter in France, from bakeries to taxis.")]),
    ("speech", "Clara", "Ça fera. Ça fera cinq euros quarante.", "fr"),
    ("speech", "Max", "Great. Now here's the real test.", "en"),
    ("silence", 3.0),
    ("speech_multi", "Max", [
        ("en", "Imagine you're at the counter. You wanted"),
        ("fr", "une tarte aux fraises"),
        ("en", ", but the baker just told you:"),
        ("fr", "Je suis désolé, il n'en reste plus."),
        ("en", "Then he says,"),
        ("fr", "Qu'est-ce que vous en pensez d'un éclair au chocolat ?"),
    ]),
    ("speech", "Clara", "Accept his suggestion, enthusiastically, in French.", "en"),
    ("silence", 5.0),
    ("speech", "Max", "Here's one good way to say it:", "en"),
    ("speech", "Clara", "Pourquoi pas ! Ça a l'air délicieux.", "fr"),
    ("speech", "Max", "\"Why not — that looks delicious.\"", "en"),
    ("silence", 3.0),
    ("speech_multi", "Clara", [("en", "So today:"), ("fr", "il n'en reste plus"), ("en", "when something's out of stock...")]),
    ("speech_multi", "Max", [("fr", "Qu'est-ce que vous en pensez de..."), ("en", "to float an alternative...")]),
    ("speech_multi", "Clara", [("en", "And"), ("fr", "pourquoi pas !"), ("en", "to say yes, easily and naturally.")]),
    ("speech", "Max", "Next time, we'll handle the opposite problem — when the thing you want is available, but you need to ask for it to go.", "en"),
    ("speech_multi", "Clara", [("en", "Ooh,"), ("fr", "à emporter."), ("en", "Can't wait.")]),
    ("speech", "Max", "Au revoir !", "fr"),
    ("speech", "Clara", "Au revoir !", "fr"),
    ("sfx", "OUTRO_STING", "podcast outro jingle: same bright acoustic guitar and accordion melody as the intro, but winding down gently, warm French cafe feel, friendly close, no vocals", 3.5),
]
